import type { Metadata } from "next";
import { Montserrat, Anton, Bonheur_Royale } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

const bonheurRoyale = Bonheur_Royale({
  variable: "--font-bonheur-royale",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${anton.variable} ${bonheurRoyale.variable} antialiased`}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
